name: main

on:
  #push:
    #branches: [ "main" ]
  schedule:
    - cron: "0 20 * * 4"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: checkout
        run: |
          BRANCH="${GITHUB_REF/#refs\/heads\//}"
          git clone --filter=blob:none --no-checkout --depth 1 --sparse https://${{ github.token }}@github.com/${{ github.repository }} .
          git sparse-checkout init --cone --sparse-index
          git -c protocol.version=2 fetch --no-tags --prune --progress --depth=1 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
          git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH
      - name: deploy
        run: |
          mkdir -p ${{ runner.temp }}/heroku-build && chmod -R 770 ${{ runner.temp }}/heroku-build
          tar --warning=no-file-changed -czf ${{ runner.temp }}/heroku-build/release.tgz --exclude .git .
          sources=`curl -X POST https://api.heroku.com/apps/${{secrets.APP}}/sources -H 'Accept: application/vnd.heroku+json; version=3' -H 'Authorization: Bearer ${{secrets.KEY}}'`
          get_url=`echo $(jq -r '.source_blob.get_url' <<< "$sources")`
          put_url=`echo $(jq -r '.source_blob.put_url' <<< "$sources")`
          curl $put_url -X PUT -H "Content-Type:" -H "Accept: application/vnd.heroku+json; version=3" --data-binary @${{ runner.temp }}/heroku-build/release.tgz
          curl -X POST https://api.heroku.com/apps/${{secrets.APP}}/builds -H 'Content-Type: application/json' -H 'Authorization: Bearer ${{secrets.KEY}}' -H 'Accept: application/vnd.heroku+json; version=3' -d "{\"source_blob\":{\"url\":\"$get_url\",\"version\":\"`git rev-parse HEAD`\"}}"
        shell: bash
